import { notFound, redirect } from "next/navigation";
import Link from "next/link";

import { PageShell } from "@/components/page-shell";
import { getOrgContext } from "@/lib/auth/admin";
import { supabaseAdmin } from "@/lib/supabase/server";
import { MiniSaasDetailClient } from "./Client";

export const dynamic = "force-dynamic";

export default async function MiniSaasDetailPage({
  params,
}: {
  params: Promise<{ id: string }>;
}) {
  const { id } = await params;
  const ctx = await getOrgContext();
  if (!ctx?.activeOrgId) redirect("/auth/signin");

  const { data } = await supabaseAdmin()
    .from("rgaios_mini_saas")
    .select(
      "id, title, description, prompt, generated_html, status, generation_meta, created_at, updated_at",
    )
    .eq("organization_id", ctx.activeOrgId)
    .eq("id", id)
    .maybeSingle();
  if (!data) notFound();

  const app = data as {
    id: string;
    title: string;
    description: string | null;
    prompt: string;
    generated_html: string | null;
    status: string;
    generation_meta: Record<string, unknown> | null;
  };

  return (
    <PageShell
      title={app.title}
      description={app.description ?? "Mini SaaS app generated by Engineering Manager"}
      actions={
        <Link
          href="/mini-saas"
          className="text-[12px] text-muted-foreground hover:text-foreground"
        >
          ← All apps
        </Link>
      }
    >
      <MiniSaasDetailClient app={app} />
    </PageShell>
  );
}
