#!/usr/bin/env bash
set -euo pipefail

# ──────────────────────────────────────────────────────────
# One-time local development bootstrap.
#   1. Brings up postgres + postgrest + caddy via docker-compose.dev.yml
#   2. Mints a service_role JWT against the dev JWT_SECRET (fixed)
#   3. Writes .env.development.local so `next dev` can read everything
#   4. Runs migrations against local postgres
#   5. Optionally seeds an initial org so you can sign in
#
# After this runs once you can iterate with:
#   npm run dev          # next dev with HMR
#   npm run dev:db:logs  # tail postgres/postgrest/caddy logs
#   npm run dev:db:down  # stop the data layer (data persists)
#   npm run dev:db:reset # nuke postgres volume and start fresh
# ──────────────────────────────────────────────────────────

bold()  { printf "\033[1m%s\033[0m\n" "$1"; }
green() { printf "\033[32m%s\033[0m\n" "$1"; }
red()   { printf "\033[31m%s\033[0m\n" "$1"; }

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

# Fixed dev JWT secret — 64 hex chars (256 bits). Local-only, never used in prod.
DEV_JWT_SECRET="0000000000000000000000000000000000000000000000000000000000000000"

bold "▸ 1. Booting docker (postgres + postgrest + caddy)"
docker compose -f docker-compose.dev.yml up -d

bold "▸ 2. Waiting for postgres to be healthy"
until docker compose -f docker-compose.dev.yml exec -T postgres pg_isready -U postgres -d rawgrowth >/dev/null 2>&1; do
  printf "."
  sleep 1
done
echo
green "✓ Postgres ready"

bold "▸ 3. Minting service_role JWT"
SERVICE_ROLE_KEY="$(npx tsx scripts/gen-jwt.ts --secret "$DEV_JWT_SECRET" --role service_role | tr -d '\n')"
green "✓ Minted (${SERVICE_ROLE_KEY:0:32}...)"

bold "▸ 4. Writing .env.development.local"
cat > .env.development.local <<EOF
# Auto-generated by scripts/dev-bootstrap.sh — do not commit.
# Next.js loads this in dev mode and overrides .env.local.

DEPLOY_MODE=self_hosted

DATABASE_URL=postgres://postgres:dev@127.0.0.1:5432/rawgrowth

JWT_SECRET=$DEV_JWT_SECRET
SUPABASE_SERVICE_ROLE_KEY=$SERVICE_ROLE_KEY

# Caddy on :3100 strips /rest/v1 and proxies to postgrest, matching prod.
NEXT_PUBLIC_SUPABASE_URL=http://127.0.0.1:3100

NEXTAUTH_URL=http://localhost:3000
NEXT_PUBLIC_APP_URL=http://localhost:3000
NEXTAUTH_SECRET=dev-only-not-for-prod-dev-only-not-for-prod
AUTH_TRUST_HOST=true

# Bearer header for /api/cron/schedule-tick — leave empty for dev (auth skipped).
CRON_SECRET=

# Seed values (only consumed if there's no org yet)
SEED_ORG_NAME=Local Dev
SEED_ORG_SLUG=local-dev
SEED_ADMIN_NAME=Dev Admin
SEED_ADMIN_EMAIL=dev@example.com
# Pre-set password so you can log in instantly without the invite flow.
SEED_ADMIN_PASSWORD=password
EOF
green "✓ .env.development.local written"

bold "▸ 5. Running migrations"
DATABASE_URL=postgres://postgres:dev@127.0.0.1:5432/rawgrowth \
  DEPLOY_MODE=self_hosted \
  npx tsx scripts/migrate.ts
green "✓ Migrations applied"

bold "▸ 6. Seeding dev org (if not already present)"
DATABASE_URL=postgres://postgres:dev@127.0.0.1:5432/rawgrowth \
  DEPLOY_MODE=self_hosted \
  JWT_SECRET="$DEV_JWT_SECRET" \
  SUPABASE_SERVICE_ROLE_KEY="$SERVICE_ROLE_KEY" \
  NEXT_PUBLIC_SUPABASE_URL=http://127.0.0.1:3100 \
  SEED_ORG_NAME="Local Dev" \
  SEED_ORG_SLUG="local-dev" \
  SEED_ADMIN_NAME="Dev Admin" \
  SEED_ADMIN_EMAIL="dev@example.com" \
  SEED_ADMIN_PASSWORD="password" \
  npx tsx scripts/seed-self-hosted.ts || true

echo
bold "════════════════════════════════════════════════════════════"
green "  Local dev is ready."
bold "════════════════════════════════════════════════════════════"
echo
echo "  Next:"
echo "    npm run dev          # Next.js with HMR on http://localhost:3000"
echo
echo "  Sign in:"
echo "    URL:      http://localhost:3000/auth/signin"
echo "    Email:    dev@example.com"
echo "    Password: password"
echo
echo "  Useful:"
echo "    npm run dev:db:logs  # tail data-layer logs"
echo "    npm run dev:db:down  # stop the data layer (data persists)"
echo "    npm run dev:db:reset # nuke postgres volume + re-bootstrap"
echo
