-- Per-department insights generated by the assignee agent (or Atlas for
-- cross-dept). Triggered when the metric-delta worker spots a > X%
-- regression or improvement vs the prior comparable window. Each row
-- carries:
--   - severity: critical | warning | info | positive
--   - reason: agent's drill-down on what caused the change
--   - suggested_action: agent's proposed fix or follow-up
--   - status: open | acknowledged | dismissed
--
-- Surfaces on /dashboard + /departments/<slug>. Operator can dismiss
-- (won't reappear for 7 days) or click "ack" (kept visible but greyed).

create table if not exists rgaios_insights (
  id              uuid primary key default gen_random_uuid(),
  organization_id uuid not null references rgaios_organizations(id) on delete cascade,
  department      text,
  kind            text not null,
  severity        text not null default 'info',
  metric          text not null,
  current_value   numeric,
  prior_value     numeric,
  delta_pct       numeric,
  title           text not null,
  reason          text,
  suggested_action text,
  status          text not null default 'open',
  generated_by_agent_id uuid references rgaios_agents(id) on delete set null,
  created_at      timestamptz not null default now(),
  acknowledged_at timestamptz,
  dismissed_at    timestamptz
);

create index if not exists idx_rgaios_insights_org_open
  on rgaios_insights (organization_id, status, created_at desc);

alter table rgaios_insights enable row level security;
drop policy if exists "service_full_access_insights" on rgaios_insights;
create policy "service_full_access_insights" on rgaios_insights
  for all using (true) with check (true);
